version: '3'
services:
  web:
    build: .
    command: bash -c 'ruby app.rb'
    volumes:
      - .:/ride_hailing_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres
    volumes:
      - postgres_data:/data
    environment:
      POSTGRES_DB: "db"
      POSTGRES_PASSWORD: "password"

volumes:
  postgres_data:
    driver: local

