version: '3'
services:
  web:
    image: danielapb/ride_hailing_app:1
    command: ruby app.rb
    volumes:
      - .:/ride_hailing_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      - PORT=8080
      - RACK_ENV=development

  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
