version: '3'
services:
  web:
    image: danielapb/ride_hailing_app:1
    command: bash -c 'ruby app.rb'
    volumes:
      - .:/ride_hailing_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
