rider_1 = Rider.create(first_name: "Daniela", last_name: "Patiño", phone: "3022032041", email: "danielaswift29@gmail.com")
rider_2 = Rider.create(first_name: "Camilo", last_name: "Sabaneta", phone: "3012131041", email: "camilosabaneta@gmail.com")
rider_3 = Rider.create(first_name: "Amanda", last_name: "Amacio", phone: "3221032041", email: "amandaamacio@gmail.com")
rider_4 = Rider.create(first_name: "Hyun", last_name: "Bin", phone: "3112141041", email: "hyunbin@gmail.com")
rider_5 = Rider.create(first_name: "Henry", last_name: "Cavill", phone: "3222133041", email: "henrycavill@gmail.com")
rider_6 = Rider.create(first_name: "Laura", last_name: "Ramirez", phone: "3125555541", email: "lauraramirez@gmail.com")

driver_1 = Driver.create(first_name: "David Luiz", last_name: "Moreira", phone: "3112032092", email: "davidluiz@gmali.com", status: "available")
driver_2 = Driver.create(first_name: "Sebastian", last_name: "Camargo", phone: "3132032092", email: "sebascamargo@gmali.com", status: "available")
driver_3 = Driver.create(first_name: "Andrea", last_name: "Cartagena", phone: "3142032092", email: "andreacartagena@gmali.com", status: "available")
driver_4 = Driver.create(first_name: "Maritza", last_name: "Cuellar", phone: "3152032092", email: "maritzacuellar@gmali.com", status: "available")
driver_5 = Driver.create(first_name: "Mauricio", last_name: "Rosa", phone: "3162032092", email: "mauriciorosa@gmali.com", status: "available")
driver_6 = Driver.create(first_name: "Luz Piedad", last_name: "Manzana", phone: "3172032092", email: "luzmanzana@gmali.com", status: "available")
